[build]
base = "" # خليها فاضية عشان يشتغل من جذر المشروع
command = "npm install && npm install --prefix client && npm run build --prefix client"
publish = "client/dist"

[build.environment]
NODE_VERSION = "20.11.1"
NODE_ENV = "production"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
