[build]
base = ""                              # الجذر
command = "npm run build"
publish = "client/dist"               # مجلد النشر من داخل client

[build.environment]
NODE_VERSION = "20.11.1"
NODE_ENV = "production"
