[build]
base = ""
command = "npm install && cd client && npm install && npm run build" # Changed this line
publish = "client/dist"

[build.environment]
NODE_VERSION = "20.11.1"
NODE_ENV = "production"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200