// <auto-generated />
using System;
using AccountingService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingService.Migrations
{
    [DbContext(typeof(AccountingContext))]
    partial class AccountingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("AccountingService.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code", "Branch")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Branch = "main",
                            Code = "1000",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(4690),
                            IsActive = true,
                            Name = "الأصول المتداولة",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = 2,
                            Branch = "main",
                            Code = "1001",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5250),
                            IsActive = true,
                            Name = "الصندوق (نقدي)",
                            ParentCode = "1000",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = 3,
                            Branch = "main",
                            Code = "1002",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5410),
                            IsActive = true,
                            Name = "البنك الأهلي",
                            ParentCode = "1000",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = 4,
                            Branch = "main",
                            Code = "1003",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5420),
                            IsActive = true,
                            Name = "البنك التجاري الدولي",
                            ParentCode = "1000",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = 5,
                            Branch = "main",
                            Code = "1010",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5420),
                            IsActive = true,
                            Name = "العملاء / المدينون",
                            ParentCode = "1000",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = 6,
                            Branch = "main",
                            Code = "1020",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5420),
                            IsActive = true,
                            Name = "مخزون",
                            ParentCode = "1000",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = 7,
                            Branch = "main",
                            Code = "1100",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5420),
                            IsActive = true,
                            Name = "الأصول الثابتة",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = 8,
                            Branch = "main",
                            Code = "1101",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5420),
                            IsActive = true,
                            Name = "عقارات ومباني",
                            ParentCode = "1100",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = 9,
                            Branch = "main",
                            Code = "1102",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5420),
                            IsActive = true,
                            Name = "سيارات وآليات",
                            ParentCode = "1100",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = 10,
                            Branch = "main",
                            Code = "1103",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5420),
                            IsActive = true,
                            Name = "أجهزة ومعدات",
                            ParentCode = "1100",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = 20,
                            Branch = "main",
                            Code = "2000",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5420),
                            IsActive = true,
                            Name = "الخصوم المتداولة",
                            Type = "Liability"
                        },
                        new
                        {
                            Id = 21,
                            Branch = "main",
                            Code = "2001",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5420),
                            IsActive = true,
                            Name = "الموردون / الدائنون",
                            ParentCode = "2000",
                            Type = "Liability"
                        },
                        new
                        {
                            Id = 22,
                            Branch = "main",
                            Code = "2002",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5420),
                            IsActive = true,
                            Name = "مصروفات مستحقة",
                            ParentCode = "2000",
                            Type = "Liability"
                        },
                        new
                        {
                            Id = 23,
                            Branch = "main",
                            Code = "2003",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5420),
                            IsActive = true,
                            Name = "ضرائب مستحقة",
                            ParentCode = "2000",
                            Type = "Liability"
                        },
                        new
                        {
                            Id = 24,
                            Branch = "main",
                            Code = "2100",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5420),
                            IsActive = true,
                            Name = "الخصوم طويلة الأجل",
                            Type = "Liability"
                        },
                        new
                        {
                            Id = 25,
                            Branch = "main",
                            Code = "2101",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5420),
                            IsActive = true,
                            Name = "قروض بنكية",
                            ParentCode = "2100",
                            Type = "Liability"
                        },
                        new
                        {
                            Id = 30,
                            Branch = "main",
                            Code = "3000",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5420),
                            IsActive = true,
                            Name = "حقوق الملكية",
                            Type = "Equity"
                        },
                        new
                        {
                            Id = 31,
                            Branch = "main",
                            Code = "3001",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5420),
                            IsActive = true,
                            Name = "رأس المال",
                            ParentCode = "3000",
                            Type = "Equity"
                        },
                        new
                        {
                            Id = 32,
                            Branch = "main",
                            Code = "3002",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5420),
                            IsActive = true,
                            Name = "الأرباح المحتجزة",
                            ParentCode = "3000",
                            Type = "Equity"
                        },
                        new
                        {
                            Id = 40,
                            Branch = "main",
                            Code = "4000",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5430),
                            IsActive = true,
                            Name = "الإيرادات",
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = 41,
                            Branch = "main",
                            Code = "4001",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5430),
                            IsActive = true,
                            Name = "إيرادات مبيعات وحدات",
                            ParentCode = "4000",
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = 42,
                            Branch = "main",
                            Code = "4002",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5430),
                            IsActive = true,
                            Name = "إيرادات إيجارات",
                            ParentCode = "4000",
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = 43,
                            Branch = "main",
                            Code = "4003",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5430),
                            IsActive = true,
                            Name = "إيرادات خدمات",
                            ParentCode = "4000",
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = 44,
                            Branch = "main",
                            Code = "4004",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5430),
                            IsActive = true,
                            Name = "إيرادات أخرى",
                            ParentCode = "4000",
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = 50,
                            Branch = "main",
                            Code = "5000",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5430),
                            IsActive = true,
                            Name = "المصروفات التشغيلية",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 51,
                            Branch = "main",
                            Code = "5001",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5430),
                            IsActive = true,
                            Name = "رواتب وأجور",
                            ParentCode = "5000",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 52,
                            Branch = "main",
                            Code = "5002",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5430),
                            IsActive = true,
                            Name = "إيجارات مدفوعة",
                            ParentCode = "5000",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 53,
                            Branch = "main",
                            Code = "5003",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5440),
                            IsActive = true,
                            Name = "كهرباء وماء",
                            ParentCode = "5000",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 54,
                            Branch = "main",
                            Code = "5004",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5440),
                            IsActive = true,
                            Name = "مواصلات ووقود",
                            ParentCode = "5000",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 55,
                            Branch = "main",
                            Code = "5005",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5440),
                            IsActive = true,
                            Name = "صيانة وإصلاح",
                            ParentCode = "5000",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 56,
                            Branch = "main",
                            Code = "5006",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5440),
                            IsActive = true,
                            Name = "دعاية وإعلان",
                            ParentCode = "5000",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 57,
                            Branch = "main",
                            Code = "5007",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5440),
                            IsActive = true,
                            Name = "مستلزمات مكتبية",
                            ParentCode = "5000",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 58,
                            Branch = "main",
                            Code = "5100",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5440),
                            IsActive = true,
                            Name = "المصروفات الإدارية",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 59,
                            Branch = "main",
                            Code = "5101",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5440),
                            IsActive = true,
                            Name = "مصاريف قانونية",
                            ParentCode = "5100",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 60,
                            Branch = "main",
                            Code = "5102",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5440),
                            IsActive = true,
                            Name = "مصاريف محاسبية",
                            ParentCode = "5100",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 61,
                            Branch = "main",
                            Code = "5103",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5440),
                            IsActive = true,
                            Name = "ضرائب ورسوم",
                            ParentCode = "5100",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 62,
                            Branch = "main",
                            Code = "5200",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5440),
                            IsActive = true,
                            Name = "تكلفة المبيعات",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 63,
                            Branch = "main",
                            Code = "5201",
                            CreatedAt = new DateTime(2026, 6, 3, 13, 24, 41, 658, DateTimeKind.Utc).AddTicks(5440),
                            IsActive = true,
                            Name = "تكلفة وحدات مباعة",
                            ParentCode = "5200",
                            Type = "Expense"
                        });
                });

            modelBuilder.Entity("AccountingService.Models.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReversedFromId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryNumber", "Branch")
                        .IsUnique();

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("AccountingService.Models.JournalEntryLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Credit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Debit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("JournalEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("JournalEntryId");

                    b.ToTable("JournalLines");
                });

            modelBuilder.Entity("AccountingService.Models.JournalEntryLine", b =>
                {
                    b.HasOne("AccountingService.Models.Account", "Account")
                        .WithMany("Lines")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountingService.Models.JournalEntry", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("AccountingService.Models.Account", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("AccountingService.Models.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
